import type { Metadata } from "next";
import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const outfitFont = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit", // Define a variable for Tailwind
});

const ovoFont = Ovo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ovo", // Define a variable for Tailwind
});

export const metadata: Metadata = {
  title: "Portfolio - Nish Patel",
  description: "Generated by Nish Patel",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${outfitFont.variable} ${ovoFont.variable} scroll-smooth`}
    >
      <body className="antialiased leading-8 overflow-x-hidden dark:bg-darktheme dark:text-white">
        {children}
      </body>
    </html>
  );
}
